### ISSUE TITLE
bitcoinAutoTrade.py 실행시 can't compare offset-naive and offset-aware datetimes 메시지가 반복됩니다.

### ISSUE THREAD

**Issue by guardhope** [youtube-jocoding/pyupbit-autotrade#7]
(base) C:\autotrade>C:/Anaconda3/python.exe c:/autotrade/bitcoinAutoTrade.py
autotrade start
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes
can't compare offset-naive and offset-aware datetimes

k값만 0.5에서 0.9로 수정하고 코드 실행했는데 위와 같은 메시지가 뜨네요.
get_ohlcv함수로 반환되는 데이터프레임을 print로 화면출력하여 보면 일자+타임존으로 되어 있는데 이 부분 때문에 다른 코드 실행에도 에러가 발생하며 문제가 되는 것 같습니다.
에러가 발생하지 않게 수정하고 싶은데 어떻게 수정하면 좋을까요?;;

**Comment by DanielFH1** [comment]
저도 지금 같은 문제를 겪고 있습니다. 시간을 연산자로 비교하는 if 조건에서 에러가 발생하는 것 같아, type을 start_time, end_time, now 모두 같게 만들어줘도 에러가 계속 발생하네요

**Comment by 2bkool** [comment]
pyupbit 모듈 업데이트 때문에 그런 같아요.

`start_time = df.index[0]`
이부분을
`start_time = df.index[0].tz_localize(None)`
이렇게 바꿔보세요

**Comment by DanielFH1** [comment]
@2bkool  덕분에 잘 해결했습니다! 감사합니다 ㅎㅎ

**Comment by guardhope** [comment]
감사합니다!
